// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxsqootkaasbradbohmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4c3Fvb3RrYWFzYnJhZGJvaG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDcxNjMsImV4cCI6MjA2MjE4MzE2M30.xYGT7tn-De8ru19T1Lz9wM2BerQ83KJUNfVE9sqsyw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);